// Code generated by risor-modgen. DO NOT EDIT.

package json

import (
	"context"
	"github.com/risor-io/risor/object"
)

// Unmarshal is a wrapper function around [unmarshal]
// that implements [object.BuiltinFunction].
func Unmarshal(ctx context.Context, args ...object.Object) object.Object {
	if len(args) != 1 {
		return object.NewArgsError("json.unmarshal", 1, len(args))
	}
	dataParam, err := object.AsBytes(args[0])
	if err != nil {
		return err
	}
	result, resultErr := unmarshal(dataParam)
	if resultErr != nil {
		return object.NewError(resultErr)
	}
	return result
}

// Valid is a wrapper function around [valid]
// that implements [object.BuiltinFunction].
func Valid(ctx context.Context, args ...object.Object) object.Object {
	if len(args) != 1 {
		return object.NewArgsError("json.valid", 1, len(args))
	}
	dataParam, err := object.AsBytes(args[0])
	if err != nil {
		return err
	}
	result := valid(dataParam)
	return object.NewBool(result)
}

// addGeneratedBuiltins adds the generated builtin wrappers to the given map.
//
// Useful if you want to write your own "Module()" function.
func addGeneratedBuiltins(builtins map[string]object.Object) map[string]object.Object {
	builtins["unmarshal"] = object.NewBuiltin("json.unmarshal", Unmarshal)
	builtins["valid"] = object.NewBuiltin("json.valid", Valid)
	return builtins
}


