
test:
	@echo "---- risor ----"
	time ../../risor ./fib.risor

	@echo "\n---- tengo ----"
	time tengo ./fib.tengo

	@echo "\n---- glua ----"
	time glua ./fib.lua

	@echo "\n---- python3 ----"
	time python3 ./fib.py

	@echo "\n---- yaegi ----"
	time yaegi ./fib.yaegi

# @echo "---- otto ----"
# time otto ./fib.js

# python 3.11.3: 1.238
# python 2.7.18: 1.712
# risor: 2.136
# tengo: 2.185
# glua: 3.169
# yaegi: 9.715
# otto: 44.454
