
test:
	time ../tamarin ./fib.tm
	time tengo ./fib.tengo
	time glua ./fib.lua
	time otto ./fib.js
	time python ./fib.py
	time yaegi ./fib.yaegi

# python 3.11.3: 1.238
# python 2.7.18: 1.712
# tamarin: 2.136
# tengo: 2.185
# glua: 3.169
# yaegi: 9.715
# otto: 44.454
