// Code generated by risor-modgen. DO NOT EDIT.

package yaml

import (
	"context"
	"github.com/risor-io/risor/object"
)

// Unmarshal is a wrapper function around [unmarshal]
// that implements [object.BuiltinFunction].
func Unmarshal(ctx context.Context, args ...object.Object) object.Object {
	if len(args) != 1 {
		return object.NewArgsError("yaml.unmarshal", 1, len(args))
	}
	dataParam, err := object.AsBytes(args[0])
	if err != nil {
		return err
	}
	result := unmarshal(dataParam)
	return result
}

// Marshal is a wrapper function around [marshal]
// that implements [object.BuiltinFunction].
func Marshal(ctx context.Context, args ...object.Object) object.Object {
	if len(args) != 1 {
		return object.NewArgsError("yaml.marshal", 1, len(args))
	}
	valueParam := args[0]
	result, resultErr := marshal(valueParam)
	if resultErr != nil {
		return object.NewError(resultErr)
	}
	return object.NewString(result)
}

// Valid is a wrapper function around [valid]
// that implements [object.BuiltinFunction].
func Valid(ctx context.Context, args ...object.Object) object.Object {
	if len(args) != 1 {
		return object.NewArgsError("yaml.valid", 1, len(args))
	}
	dataParam, err := object.AsBytes(args[0])
	if err != nil {
		return err
	}
	result := valid(dataParam)
	return object.NewBool(result)
}

// addGeneratedBuiltins adds the generated builtin wrappers to the given map.
//
// Useful if you want to write your own "Module()" function.
func addGeneratedBuiltins(builtins map[string]object.Object) map[string]object.Object {
	builtins["unmarshal"] = object.NewBuiltin("yaml.unmarshal", Unmarshal)
	builtins["marshal"] = object.NewBuiltin("yaml.marshal", Marshal)
	builtins["valid"] = object.NewBuiltin("yaml.valid", Valid)
	return builtins
}

// The "Module()" function can be disabled with "//risor:generate no-module-func"

// Module returns the Risor module object with all the associated builtin
// functions.
func Module() *object.Module {
	return object.NewBuiltinsModule("yaml", addGeneratedBuiltins(map[string]object.Object{}))
}

